const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8'),source=[...html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('worker-source'))[2];
let messages=[];const context=vm.createContext({performance,Blob,Response,DecompressionStream,TextDecoder,URL,fetch:async()=>new Response(fs.readFileSync(__dirname+'/sample-five-million.csv.gz')),postMessage:m=>messages.push(m)});
vm.runInContext(source,context);
(async()=>{await context.onmessage({data:{type:'url',url:'https://example.test/sample-five-million.csv.gz'}});const loaded=messages.find(m=>m.type==='loaded');assert.ok(loaded,JSON.stringify(messages));const meta=loaded.meta;assert.equal(meta.detail,5000000);assert.equal(meta.summary,108);assert.equal(meta.gpuSafe,true);
const ALL=4294967295;messages=[];await context.onmessage({data:{type:'cpu',f:[ALL,ALL,ALL,ALL,0]}});const detail=messages[0],totals=Array.from(detail.result).reduce((a,v,i)=>(a[i%3]+=v,a),[0,0,0]);assert.deepEqual(totals,[5000000,2497135264,1247484231]);messages=[];await context.onmessage({data:{type:'cpu',f:[ALL,ALL,ALL,ALL,1]}});for(let i=0;i<detail.result.length;i++)if(i%3!==0)assert.equal(detail.result[i],messages[0].result[i]);
// Independent emulation of two storage-buffer chunks with the same 256-row aligned boundaries.
const perChunk=Math.floor((128*1024*1024/28)/256)*256,groups=meta.pref.length*meta.tag.length,bins=new Uint32Array(256*groups*3),rows=new Uint32Array(loaded.buffer);
for(let start=0;start<meta.n;start+=perChunk)for(let local=0;local<Math.min(perChunk,meta.n-start);local++){const i=(start+local)*7;if(rows[i+6])continue;const j=((local%256)*groups+rows[i]*meta.tag.length+rows[i+5])*3;bins[j]++;bins[j+1]+=rows[i+3];bins[j+2]+=rows[i+4];}
const reduced=Array(groups*3).fill(0);for(let i=0;i<bins.length;i++)reduced[i%reduced.length]+=bins[i];assert.deepEqual(reduced,Array.from(detail.result));
console.log(JSON.stringify({detail:meta.detail,summary:meta.summary,gzipBytes:meta.io.inputBytes,arrayMiB:loaded.buffer.byteLength/2**20,gzipDecodeMs:meta.io.decodeMs,parseMs:meta.parseMs,cpuFirstMs:detail.ms,gpuSafe:meta.gpuSafe,chunks:Math.ceil(meta.n/perChunk),rssMiB:process.memoryUsage().rss/2**20,totals},null,2));console.log('PASS: existing 5M gzip, parser, totals, summary values and multi-chunk shader layout. Actual browser/GPU speed not measured.');
})().catch(e=>{console.error(e);process.exitCode=1;});
